CREATE TABLE IF NOT EXISTS SQL_PRACTICE.FACT_ORDER_ITEMS
(
    ORDER_ITEM_SK NUMBER AUTOINCREMENT,

    ORDER_ID NUMBER,
    LINE_ITEM_ID NUMBER,

    PRODUCT_SK NUMBER,
    VARIANT_ID NUMBER,

    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(18,2),
    TOTAL_DISCOUNT NUMBER(18,2),

    GROSS_AMOUNT NUMBER(18,2),
    NET_AMOUNT NUMBER(18,2),

    ORDER_CREATED_AT TIMESTAMP_TZ,
    LOAD_DATE TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);