INSERT INTO SQL_PRACTICE.FACT_ORDER_ITEMS
(
    ORDER_ID,
    LINE_ITEM_ID,
    PRODUCT_SK,
    VARIANT_ID,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_DISCOUNT,
    GROSS_AMOUNT,
    NET_AMOUNT,
    ORDER_CREATED_AT
)
SELECT
    S.ORDER_ID,
    S.LINE_ITEM_ID,
    P.PRODUCT_SK,
    S.VARIANT_ID,
    S.QUANTITY,
    S.UNIT_PRICE,
    S.TOTAL_DISCOUNT,
    S.QUANTITY * S.UNIT_PRICE AS GROSS_AMOUNT,
    (S.QUANTITY * S.UNIT_PRICE) - S.TOTAL_DISCOUNT AS NET_AMOUNT,
    S.ORDER_CREATED_AT
FROM SQL_PRACTICE.STG_ORDER_ITEMS S
LEFT JOIN SQL_PRACTICE.DIM_PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID
   AND P.IS_CURRENT = TRUE;