CREATE TABLE IF NOT EXISTS SQL_PRACTICE.DIM_CUSTOMER
(
    CUSTOMER_SK NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    default_state varchar,
    COUNTRY VARCHAR,
    ZIP VARCHAR,
    CREATED_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ,
    RECORD_START_DATE TIMESTAMP_TZ,
    RECORD_END_DATE TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN,
    LOAD_DATE TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
