CREATE OR REPLACE TABLE SQL_PRACTICE.DIM_PRODUCT
(
    PRODUCT_SK NUMBER AUTOINCREMENT,
    PRODUCT_ID NUMBER,
    TITLE VARCHAR,
    HANDLE VARCHAR,
    VENDOR VARCHAR,
    PRODUCT_TYPE VARCHAR,
    STATUS VARCHAR,
    TAGS VARCHAR,
    IS_GIFT_CARD BOOLEAN,
    TRACKS_INVENTORY BOOLEAN,
    CREATED_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ,
    RECORD_START_DATE TIMESTAMP_TZ,
    RECORD_END_DATE TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN,
    LOAD_DATE TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);