-- Expire the current version when product attributes change

UPDATE SQL_PRACTICE.DIM_PRODUCT D
SET
    IS_CURRENT = FALSE,
    RECORD_END_DATE = CURRENT_TIMESTAMP()
FROM SQL_PRACTICE.STG_PRODUCTS S
WHERE D.PRODUCT_ID = S.ID
  AND D.IS_CURRENT = TRUE
  AND (
       NVL(D.TITLE,'') <> NVL(S.TITLE,'')
    OR NVL(D.HANDLE,'') <> NVL(S.HANDLE,'')
    OR NVL(D.VENDOR,'') <> NVL(S.VENDOR,'')
    OR NVL(D.PRODUCT_TYPE,'') <> NVL(S.PRODUCT_TYPE,'')
    OR NVL(D.STATUS,'') <> NVL(S.STATUS,'')
    OR NVL(D.TAGS,'') <> NVL(S.TAGS,'')
    OR NVL(D.IS_GIFT_CARD,FALSE) <> NVL(S.IS_GIFT_CARD,FALSE)
    OR NVL(D.TRACKS_INVENTORY,FALSE) <> NVL(S.TRACKS_INVENTORY,FALSE)
);

-- Insert new products and new versions of changed products

INSERT INTO SQL_PRACTICE.DIM_PRODUCT
(
    PRODUCT_ID,
    TITLE,
    HANDLE,
    VENDOR,
    PRODUCT_TYPE,
    STATUS,
    TAGS,
    IS_GIFT_CARD,
    TRACKS_INVENTORY,
    CREATED_AT,
    UPDATED_AT,
    RECORD_START_DATE,
    RECORD_END_DATE,
    IS_CURRENT
)
SELECT
    S.ID,
    S.TITLE,
    S.HANDLE,
    S.VENDOR,
    S.PRODUCT_TYPE,
    S.STATUS,
    S.TAGS,
    S.IS_GIFT_CARD,
    S.TRACKS_INVENTORY,
    S.CREATED_AT,
    S.UPDATED_AT,
    CURRENT_TIMESTAMP(),
    '9999-12-31'::TIMESTAMP_TZ,
    TRUE
FROM SQL_PRACTICE.STG_PRODUCTS S
WHERE NOT EXISTS
(
    SELECT 1
    FROM SQL_PRACTICE.DIM_PRODUCT D
    WHERE D.PRODUCT_ID = S.ID
      AND D.IS_CURRENT = TRUE
);