CREATE OR REPLACE VIEW SQL_PRACTICE.STG_ORDER_ITEMS AS
SELECT
    O.ID AS ORDER_ID,
    F.VALUE:id::NUMBER AS LINE_ITEM_ID,
    F.VALUE:product_id::NUMBER AS PRODUCT_ID,
    F.VALUE:variant_id::NUMBER AS VARIANT_ID,
    F.VALUE:title::STRING AS PRODUCT_TITLE,
    F.VALUE:variant_title::STRING AS VARIANT_TITLE,
    F.VALUE:sku::STRING AS SKU,
    F.VALUE:vendor::STRING AS VENDOR,
    F.VALUE:quantity::NUMBER AS QUANTITY,
    F.VALUE:price::NUMBER(18,2) AS UNIT_PRICE,
    F.VALUE:total_discount::NUMBER(18,2) AS TOTAL_DISCOUNT,
    F.VALUE:requires_shipping::BOOLEAN AS REQUIRES_SHIPPING,
    F.VALUE:taxable::BOOLEAN AS TAXABLE,
    O.CREATED_AT AS ORDER_CREATED_AT,
    O.UPDATED_AT AS ORDER_UPDATED_AT,
    O._AIRBYTE_EXTRACTED_AT
FROM SQL_PRACTICE.SHOPIFY_ORDERS O,
LATERAL FLATTEN(INPUT => O.LINE_ITEMS) F;